### ISSUE TITLE
Weird new Matrix behaviour

### ISSUE THREAD

**Issue by dill** [atlanticbrs/CTMCdive#2]
I've made an update to change the way sparse matrices are created, which seems to have broken with the new version of the `Matrix` package. Unsure if this breaks things on the Duke server though @williamcioffi, so please do let me know if so and I'll try to switch based on package version or something.

**Comment by williamcioffi** [comment]
I'm still testing this, but seems to be working so far.

Note: I'll put this here for now, but to compile TMB with the new version of matrix (`install.packages('TMB', type = 'source'`) on an M1 arm mac, I had to add a file`~/.R/Makevars` with the following (as suggested [here](https://stackoverflow.com/questions/69639782/installing-gfortran-on-macbook-with-apple-m1-chip-for-use-in-r
)):

```
FC = /opt/homebrew/Cellar/gcc/12.2.0/bin/gfortran
F77 = /opt/homebrew/Cellar/gcc/12.2.0/bin/gfortran
FLIBS = -L/opt/homebrew/Cellar/gcc/12.2.0/lib/gcc/12
```

Note also that these paths are specific to my version of gfortran installed via homebrew. Maybe should add a note to the readme? Although it is a general problem of compiling packages that need gfortran (e.g., TMB, Matrix) on the new arm macs, I had trouble finding a good solution. I think they might be assuming you are doing [this](https://mac.r-project.org/tools/) like for compiling R itself, but if it works I'd prefer homebrew.

edit: fixed home path

**Comment by williamcioffi** [comment]
A couple of observations for running this on the cluster:
- Unless something is going on with our cluster, it seems to be much slower this time.
- I have gotten a couple of errors of the following type, but the entire job hasn't ended yet, so I haven't been able to check where it is occurring:
```
Error in .local(x, ...) : 
  cs_lu(A) failed: near-singular A (or out of memory)
```
Will try to take a closer look when the job ends, as well as rolling back versions to see if I can reproduce the earlier positive results.

**Comment by dill** [comment]
Indeed, in testing on our server here in St Andrews I get:

```
Error : no method or default for coercing “matrix” to “dMatrix”
```

So I probably need to fiddle with this more...

**Comment by dill** [comment]
Probably this also needs to be handled when the new version comes out and the "fix" to this has been implemented (see [here](https://twitter.com/FinnLindgren/status/1589610452451196928?s=20&t=qqX2eJesK1CQ8YU7ZKHJ-A) and [here](https://r-forge.r-project.org/scm/viewvc.php/pkg/Matrix/inst/NEWS.Rd?view=markup&root=matrix).

**Comment by dill** [comment]
Regarding `Makevars` on M1 Macs... Phew, good question. I think it's generally the case that most people will use the `gfortran` provided by R, rather than `homebrew` (I do the former). Maybe we can assume that if you've installed `gfortran` via `homebrew` you know how to do this?

For Windows there is a `Makevars.win`, I wonder if there is something equivalent for M1?

Also I think your `homebrew` location is non-standard? I think use of `/opt/Cellar` was deprecated and now install is in `/usr/local/Cellar`? Or is this an M1 thing too?

**Comment by williamcioffi** [comment]
Fair enough on all points! Let me know if you want me to test anything. Also happy to roll back to an early version of Matrix (1.4.1?) temporarily if you think that's more expedient for the current analysis and won't mess anything else up? Longterm it'd be nice to work with the latest version, of course.

as for the M1: homebrew I think they did switch to installing into `/opt` for M1 to avoid some weirdness they were having on the new platform. I'm old school so I like it there anyway. I agree probably too tangential for the docs here, but I did want to write it down for myself at least so I could remember.

**Comment by dill** [comment]
Definitely useful having it written down somewhere!

On the other issues you ran into: I'm running again on our server to see what happens and will look out for these issues as I run through the outstanding issues [here](https://github.com/atlanticbrs/DATAPREPsattagCTMC/issues/3#issuecomment-1304691709).

**Comment by dill** [comment]
The 

```
Error in .local(x, ...) : 
  cs_lu(A) failed: near-singular A (or out of memory)
```

issue should be fixed now. It was happening when the matrix inverse was calculated via `solve`, which is not guaranteed to work. Now it will try, if it fails will try using a pseudo-inverse method and else returns `NULL` for the variance-covariance matrix (probably something has gone wrong in this case anyway, but we shouldn't totally crash because of it).

**Comment by dill** [comment]
Scratch that, it looks like there are other situations when this happens... Sorry.

**Comment by dill** [comment]
closing this issue but noting that we had to revert the `Matrix` package fix, but in newer versions of their package the old code in `CTMCdive` works again!
